### PR TITLE
restructure mermaid markdown output

### LINKED ISSUE #4: Re-Design mermaid markdown generation
## Please describe what you would like to see in this project

The current mermaid markdown creates a graph that is difficult to parse visually and is even broken in rendering because of fundamental changes to the engine.

- This needs a re-design and possibly needs to be moved out of the go-dgraph altogether.
- It likely needs to render only the "good" path of the workflow for more readability as workflows get complicated (eliminating error paths).
- The Inputs subgraph needs to be corrected as it is currently broken.
- The graphs may render better in Left-Right format instead of the current Top-Down.
- We need a way to graph a complete workflow with sub-workflows that show the relationships.

### PR DESCRIPTION
**Pull request by dustinblack**
## Changes introduced with this PR

Mostly address issue #4. Removes the input subgraph, which has been broken for a while since another change made the individual input nodes no longer visible to the function. Separates the success path from the error path, and adds some markdown comments to denote them, making it simple to copy-paste only the success path to the mermaid renderer for a simpler workflow chart. Changes the rendering from TopDown style to LeftRight style.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dustinblack** [comment]
New sample output:

```
%% Mermaid markdown workflow
flowchart LR
%% Success path
steps.sysbench_memory.outputs.success-->outputs.success
steps.pcp.outputs-->steps.pcp.outputs.success
steps.pcp.cancelled-->steps.pcp.outputs
steps.sysbench_memory.cancelled-->steps.sysbench_memory.outputs
steps.sysbench_memory.running-->steps.sysbench_memory.outputs
steps.pcp.outputs.success-->outputs.success
steps.pcp.starting-->steps.pcp.starting.started
steps.pcp.starting-->steps.pcp.running
steps.sysbench_memory.deploy-->steps.sysbench_memory.starting
steps.sysbench_memory.outputs-->steps.pcp.cancelled
steps.sysbench_memory.outputs-->steps.sysbench_memory.outputs.success
steps.pcp.running-->steps.pcp.outputs
input-->steps.sysbench_memory.starting
input-->steps.pcp.starting
steps.pcp.starting.started-->steps.sysbench_memory.starting
steps.pcp.deploy-->steps.pcp.starting
steps.sysbench_memory.starting-->steps.sysbench_memory.running
steps.sysbench_memory.starting-->steps.sysbench_memory.starting.started
%% Error path
steps.pcp.outputs-->steps.pcp.outputs.error
steps.pcp.cancelled-->steps.pcp.crashed
steps.pcp.cancelled-->steps.pcp.deploy_failed
steps.sysbench_memory.cancelled-->steps.sysbench_memory.crashed
steps.sysbench_memory.cancelled-->steps.sysbench_memory.deploy_failed
steps.sysbench_memory.deploy_failed-->steps.sysbench_memory.deploy_failed.error
steps.sysbench_memory.running-->steps.sysbench_memory.crashed
steps.pcp.starting-->steps.pcp.crashed
steps.pcp.deploy_failed-->steps.pcp.deploy_failed.error
steps.sysbench_memory.deploy-->steps.sysbench_memory.deploy_failed
steps.sysbench_memory.outputs-->steps.sysbench_memory.outputs.error
steps.pcp.running-->steps.pcp.crashed
steps.sysbench_memory.crashed-->steps.sysbench_memory.crashed.error
steps.pcp.deploy-->steps.pcp.deploy_failed
steps.sysbench_memory.starting-->steps.sysbench_memory.crashed
steps.pcp.crashed-->steps.pcp.crashed.error
%% Mermaid end
```

And rendering only the success path:
```mermaid
%% Mermaid markdown workflow
flowchart LR
%% Success path
steps.sysbench_memory.outputs.success-->outputs.success
steps.pcp.outputs-->steps.pcp.outputs.success
steps.pcp.cancelled-->steps.pcp.outputs
steps.sysbench_memory.cancelled-->steps.sysbench_memory.outputs
steps.sysbench_memory.running-->steps.sysbench_memory.outputs
steps.pcp.outputs.success-->outputs.success
steps.pcp.starting-->steps.pcp.starting.started
steps.pcp.starting-->steps.pcp.running
steps.sysbench_memory.deploy-->steps.sysbench_memory.starting
steps.sysbench_memory.outputs-->steps.pcp.cancelled
steps.sysbench_memory.outputs-->steps.sysbench_memory.outputs.success
steps.pcp.running-->steps.pcp.outputs
input-->steps.sysbench_memory.starting
input-->steps.pcp.starting
steps.pcp.starting.started-->steps.sysbench_memory.starting
steps.pcp.deploy-->steps.pcp.starting
steps.sysbench_memory.starting-->steps.sysbench_memory.running
steps.sysbench_memory.starting-->steps.sysbench_memory.starting.started
```

File: dg.go [hunk 1]
```diff
@@ -24,20 +25,32 @@ type directedGraph[NodeType any] struct {
...
-	}
+    result := []string{
+        "%% Mermaid markdown workflow",
+        "flowchart LR",
+        "%% Success path",
     }
-    result = append(result, "end")
+
+    errorPath := []string{"%% Error path"}
+    errorPathRegex, _ := regexp.Compile("error|crashed|failed|deploy_failed")
```
Comment (jaredoconnell) [inline dg.go]: It may make sense to make this a global, so it just runs once instead of every time this is called.

File: dg.go [hunk 2]
```diff
@@ -24,20 +25,32 @@ type directedGraph[NodeType any] struct {
...
+
     for source, d := range d.connectionsFromNode {
         for destination := range d {
-            result = append(result, fmt.Sprintf("%s-->%s", source, destination))
+            destinationNodes := strings.Split(destination, ".")
+            match := errorPathRegex.MatchString(
```
Comment (jaredoconnell) [inline dg.go]: I don't think this variable name is a good one. I'd do something like `isErrorPath`

File: dg.go (hunk 1 above)
Comment (jaredoconnell) [reply dg.go]: Another concern is this is hard-coded. I wonder if it would be worth the effort to make this an input. Like a list of strings that matches an error type, or even more generically, a map of category type to a pattern or list of values that matches that category.

What do you think, @webbnh?

Comment (dustinblack) [reply dg.go]: I thought about the hard-coded problem, but I don't know enough of the code base or golang to see a better approach right now.

File: dg.go (hunk 2 above)
Comment (dustinblack) [reply dg.go]: Done.

File: dg.go (hunk 1 above)
Comment (dustinblack) [reply dg.go]: > It may make sense to make this a global, so it just runs once instead of every time this is called.

Done.

Comment (dbutenhof) [reply dg.go]: > Another concern is this is hard-coded. I wonder if it would be worth the effort to make this an input. Like a list of strings that matches an error type, or even more generically, a map of category type to a pattern or list of values that matches that category.

Yeah, I wondered about the hardcoded list, too.

How many difference patterns are we likely to have, and what informs the change?

**Review by dbutenhof — APPROVED** [review]

File: dg.go (hunk 1 above)
Comment (dustinblack) [reply dg.go]: > Yeah, I wondered about the hardcoded list, too.
> 
> How many difference patterns are we likely to have, and what informs the change?

These are workflow step "nodes" and could change with any alterations to the workflow. AFAIK we don't define anywhere else which nodes are the "error" path and which are the "success" path like this. In principle, it would make more sense for those paths to be defined somehow in the workflow and inherited here, but for the sake of this improvement alone, I'm inclined to keep it this way for now and avoid external change dependencies just for the sake of some improved debug logging. But maybe I should open an issue for the engine to define these paths there in the future.

File: dg.go [hunk 3]
```diff
@@ -23,21 +24,34 @@ type directedGraph[NodeType any] struct {
...
+
+    errorPath := []string{"%% Error path"}
+
     for source, d := range d.connectionsFromNode {
         for destination := range d {
-            result = append(result, fmt.Sprintf("%s-->%s", source, destination))
+            destinationNodes := strings.Split(destination, ".")
+            isErrorPath := errorPathRegex.MatchString(
+                destinationNodes[len(destinationNodes)-1],
+            )
```
Comment (webbnh) [inline dg.go]: First, should we be using a full match instead of a partial match (i.e., `^(?:error|crashed|failed|deploy_failed)$`)?

Second, since we're already doing a regex match, we can skip splitting the string if we use the appropriate pattern: `\.(?:error|crashed|failed|deploy_failed)$`.

File: dg.go [hunk 4]
```diff
@@ -23,21 +24,34 @@ type directedGraph[NodeType any] struct {
...
+            if (isErrorPath) {
+                errorPath = append(errorPath, fmt.Sprintf("%s-->%s", source, destination))
+            } else {
+                result = append(result, fmt.Sprintf("%s-->%s", source, destination))
+            }
```
Comment (webbnh) [inline dg.go]: Since the output pattern is the same regardless of whether it's a success or error path, we should either use a constant for the format string or just factor out the formatting operation:
```go
            line := fmt.Sprintf("%s-->%s", source, destination)
            if (isErrorPath) {
                errorPath = append(errorPath, line)
            } else {
                result = append(result, line)
            }
```

File: dg.go [hunk 5]
```diff
@@ -23,21 +24,34 @@ type directedGraph[NodeType any] struct {
     connectionsToNode   map[string]map[string]struct{}
 }
 
+var errorPathRegex, _ = regexp.Compile("error|crashed|failed|deploy_failed")
+
 func (d *directedGraph[NodeType]) Mermaid() string {
```
Comment (webbnh) [inline dg.go]: Is there any testing of `Mermaid()`?  If not, should there be?  (If there were, it could confirm that the `Compile()` call returns no error, rather than just ignoring it....)

File: dg.go (hunk 1 above)
Comment (webbnh) [reply dg.go]: > I wonder if it would be worth the effort to make this an input.

Unless this is currently or soon to be called from multiple places, moving the list from a global to the caller is just kicking the can up the call stack -- it doesn't really solve any problem (and introduces additional complexity).

The answer might be different if there were a canonical list defined somewhere else, but I'm not hearing that there is.  And, as Dustin implies, we can go with the hard-coded list in this PR and iterate once we have a better solution.

**Review by webbnh — APPROVED** [review]
Just the usual collection of pointed questions and suggestions.

File: dg.go (hunk 5 above)
Comment (dustinblack) [reply dg.go]: I don't see a test for `Mermaid()` currently. I'm not sure of the value of checking the call return of `Compile()` since the regex string is statically defined.

**Review by jaredoconnell — APPROVED** [review]
Looks good once the other reviewers confirm that your changes are good. Regarding hard-coding error cases, I think that works for now and can easily be changed later.

**Review by dbutenhof — APPROVED** [review]

File: dg.go (hunk 5 above)
Comment (webbnh) [reply dg.go]: If the regex string somehow went bad, no one would know (because we don't check the error status from the compilation, and because this function is rarely used)...until the next time we tried to produce a Mermaid graph (which might be _much_ later).

I don't know what the options are for checking values at global scope, and, as you say, given that the string is statically defined, we certainly don't need to check for errors on every run...which is why it would be handy to check it (only) when we are already checking the code for errors...but, we aren't checking this code, so...nevermind.

**Review by webbnh — APPROVED** [review]
Looks good!

**Comment by webbnh** [comment]
This PR looks like it is ready to merged, except for the two open conversations from Jared; however, I _think_ he has [given permission](https://github.com/arcalot/go-dgraph/pull/12#pullrequestreview-1896482961) to merge it despite those.
